### ISSUE TITLE
LIVE (2309) and BE ALIVE (1422)

### ISSUE THREAD

**Issue by chrzyki** [concepticon/concepticon-data#797] opened 2020-03-20 11:14 UTC
Both have the same definition. Might benefit from refinements?

**Comment by AnnikaTjuka** [comment] 2020-03-20 11:19
This looks like a duplicate.

**Comment by AnnikaTjuka** [comment] 2020-03-20 11:23
The mappings for LIVE are: 
Rzymski-2020-1624-1589 LIVE [english]  (But also: Rzymski-2020-1624-219 BE ALIVE [english])
Not sure why Savelyev-2020-254-122 live (v.) [english] is mapped to LIVE.

**Comment by Schweikhard** [comment] 2020-03-20 11:28
LIVE is already marked as a duplicate of BE ALIVE.

Perhaps concepticon test could also test for whether anything is mapped to a retired concept?

**Comment by LinguList** [comment] 2020-03-20 11:32
I think, this is accounted for in tests!

**Closed** 2020-06-08 08:59 UTC
Labels: concept definitions
