### ISSUE TITLE
Problem with `map_concepts` command

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#704] opened 2020-01-05 12:08 UTC
I ran into a problem with the `map_concepts` command while mapping an English norm data list.

The error message that I received was "Your gloss is empty" which is why I tried to find the error in my list. At some point I used the `make_app` command and received an error message with "KeyError: '<<<<<<< HEAD'". The `concepticon test` command did not return an error message.

I also downloaded an older Concepticon version (2.2.1) and everything worked fine.

By chance, we found the issue in one of the pull requests: #692 ([here](https://github.com/concepticon/concepticon-data/commit/d10d147186ced03e9ca9ae4412034a2f9aeead9b))
While solving a merge conflict (which probably occurred because a latter PR was merged before the previous PR was merged into the master branch) the two files **map-en.tsv** and **map-fr.tsv** were changed. Git must have included the '<<<<<<< HEAD' because of the merge. 

The reason why I describe this in such detail is twofold:

1. Can we just replace the two files map-en.tsv and map-fr.tsv with former versions?
2. Would it make sense to include this case in the `concepticon test` command?

**Comment by Kristina-Pianykh** [comment] 2020-01-05 17:33
If you try to automatically map concepts with `map_concepts` and get the error "Your gloss is empty", it might be because the column with the concepts is not named "GLOSS". Try to rename it.

As far as I've figured, a merge conflict generates a duplicate of the part where your changes are inconsistent with the data in the master branch. Thus '<<<<<<< HEAD', indicating where in the file this conflict has to be resolved. I usually do that manually.

**Comment by LinguList** [comment] 2020-01-05 17:45
yes, it is an error in your source file. They excpect something such as "Swadesh-1955-200" as key, but you have "<<<" indicating that something was not merged. Find the line, delete it, and it will be fine.

**Comment by AnnikaTjuka** [comment] 2020-01-05 19:22
I think the problem isn't my source file but rather the **map-en.tsv** in the current concepticon-data master branch.

Background info: I cloned the current concepticon-data repository because I set up a new folder structure.

**How to reproduce:** The error can be reproduced if one clones the current concepticon-data master branch and tries `map_concepts` with a list of her/his choice.

The error "Your gloss is empty" occurred in the following scenarios:
1. My norm data list with several columns including `ID`, `ENGLISH`, `NUMBER`.
2. An example list with only two concepts with values in the columns: `ID`, `GLOSS`, `NUMBER`.
3. An existing concept list in the repository which was already mapped.

The file [map-en.tsv](https://github.com/concepticon/concepticon-data/blob/master/mappings/map-en.tsv) in the current repository has 157 matches for "<<<<<<< HEAD": https://github.com/concepticon/concepticon-data/blob/master/mappings/map-en.tsv

(The map-fr.tsv file seems to be unchanged but was pushed in the same merge  #692 (see merge commit with changed files:
https://github.com/concepticon/concepticon-data/commit/d10d147186ced03e9ca9ae4412034a2f9aeead9b )

**Comment by LinguList** [comment] 2020-01-06 06:18
Then just run the comment that recreates the mappings: concepticon recreate_mappings or similar.

**Comment by LinguList** [comment] 2020-01-06 06:19
This was obviously not done by the last PR (and it should not always been done), and the errors slipped our tests.

**Comment by AnnikaTjuka** [comment] 2020-01-06 07:59
Ah ok, I ran `concepticon make_linkdata` and it recreated several mappings. I will commit the changes in my current PR #699 so that the correct version of map-en.tsv is pushed to the master branch.

**Closed** 2020-01-06 08:06 UTC
