### ISSUE TITLE
Holle's Lists on Indonesian Languages

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#220] opened 2016-10-18 13:27 UTC
Anthony Grant pointed me to these lists and provided some scans, but they are unfortunately REALLY large, and the scans are partially not readable, but it seems to be a larger collection:
- http://www.worldcat.org/title/holle-lists-vocabularies-in-languages-of-indonesia/oclc/9687143

Maybe we should wait until we find a linguist who has digitized all this data, so that we can then take action.

**Comment by SimonGreenhill** [comment] 2018-05-22 11:00
These are 1486 words, 3 version (1894, 1904/11, 1931). The lists were all republished in Stokhof 1982, 1983. 

A good scan of the wordlist is here: 

![image](https://user-images.githubusercontent.com/220169/40358616-240954f8-5dc0-11e8-83e3-a6764e6af862.png)

**Comment by SimonGreenhill** [comment] 2018-05-22 11:47
has lots of fun things to define as it was partly designed to make bible translation easier (e.g. 'supreme being', 'virginity', 'prostitution', 'vital spirit', 'filing of teeth')

**Comment by xrotwang** [comment] 2024-01-23 12:59
Duplicate of #1324

**Closed by xrotwang** 2024-01-23 12:59 UTC
Labels: new concept list
